#!/bin/zsh

GIT_STATUS=$(git status --porcelain)

echo "🔍 린트 검사를 시작합니다."

if ! LOG=$(pnpm lint 2>&1) || [ "$GIT_STATUS" != "$(git status --porcelain)" ]; then
  echo "❌ 린트 검사에 실패했습니다."
  echo "$LOG"
  exit 1
else
  echo "✅ 린트 검사를 통과했습니다."
fi

echo "🔍 타입 검사를 시작합니다."

if ! LOG=$(pnpm type-check 2>&1); then
  echo "❌ 타입 검사에 실패했습니다."
  echo "$LOG"
  exit 1
else
  echo "✅ 타입 검사를 통과했습니다."
fi

exit 0